### PR TITLE
Fix bugs regarding timepicker component

### LINKED ISSUE #18: Fix timepicker component styling
Since we overrode the `MuiButton`'s css styling, all `MuiButton` embedded got changed as well. 

Screenshot 2020-03-22 at 12 31 47 AM

### LINKED ISSUE #23: Automate timepicker component on event form
When user select a particular `start` time, the `end` time should be changed accordingly so it's ahead of the `start` time

### PR DESCRIPTION
**Pull request by welvin21**
Closes #18, closes #23

### CODE REVIEW

File: src/components/routes/homepage/EventTimePicker.js [hunk 1]
```diff
@@ -1,25 +1,35 @@
...
-export const EventTimePicker = ({ value, setValue }) => {
+export const EventTimePicker = ({ value, handleTimeChange }) => {
   const classes = useStyles();
 
+  const theme = useTheme();
+  const { overrides } = theme;
+  const timePickerTheme = {
+    ...theme,
+    overrides: { ...overrides, MuiButton: {} }
+  }; // removes MuiButton override styling
```
Comment (98sean98) [inline src/components/routes/homepage/EventTimePicker.js:21]: @welvin21 I changed the approach because `overrides` object may contain potential components in the future that we want to pass down

Comment (welvin21) [reply src/components/routes/homepage/EventTimePicker.js:21]: @98sean98 Ohh yeah, that's true, thanks for pointing out 👍

**Review by utkarsh867 — APPROVED** [review]
