### PR TITLE
Fix mutation bug

### LINKED ISSUE #22: Handle createEvent mutation correctly when null is returned
When `null` is returned from `phoenix`, `raven` should throw an error to user

### PR DESCRIPTION
**Pull request by welvin21**
Closes #22 

initially when `null` is returned from phoenix (usually because s3 upload or delete fails), client still prompts success message to the user.

### CODE REVIEW

File: src/functions/createModal.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
+/**
+ * @author welvin21
+ * This function creates a modal
+ * based on a unique key which determines the modal message
+ * @param  {string} modalKey modal key which is unique to a particular modal message
+ * @return {object}          an object describing the details of the modal
+ */
+export const createModal = modalKey => {
```
Comment (98sean98) [inline src/functions/createModal.js]: probably should rename this to `createModalMessage` instead of `createModal` which can be confused as a function that creates a react component

**Review by 98sean98 — CHANGES_REQUESTED** [review]
rename `createModal`

File: src/functions/createModal.js (hunk 1 above)
Comment (welvin21) [reply src/functions/createModal.js]: alrightt, will make the changes in a moment

**Review by 98sean98 — APPROVED** [review]
`createModalMessage` should be used whenever our `Modal` component is used
